# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/simplifi/Desktop/C/EE459Spring2019

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/simplifi/Desktop/C/EE459Spring2019

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/simplifi/Desktop/C/EE459Spring2019/CMakeFiles /home/simplifi/Desktop/C/EE459Spring2019/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/simplifi/Desktop/C/EE459Spring2019/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named strip

# Build rule for target.
strip: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 strip
.PHONY : strip

# fast build rule for target.
strip/fast:
	$(MAKE) -f CMakeFiles/strip.dir/build.make CMakeFiles/strip.dir/build
.PHONY : strip/fast

#=============================================================================
# Target rules for targets named fuses

# Build rule for target.
fuses: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fuses
.PHONY : fuses

# fast build rule for target.
fuses/fast:
	$(MAKE) -f CMakeFiles/fuses.dir/build.make CMakeFiles/fuses.dir/build
.PHONY : fuses/fast

#=============================================================================
# Target rules for targets named hex

# Build rule for target.
hex: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hex
.PHONY : hex

# fast build rule for target.
hex/fast:
	$(MAKE) -f CMakeFiles/hex.dir/build.make CMakeFiles/hex.dir/build
.PHONY : hex/fast

#=============================================================================
# Target rules for targets named eeprom

# Build rule for target.
eeprom: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 eeprom
.PHONY : eeprom

# fast build rule for target.
eeprom/fast:
	$(MAKE) -f CMakeFiles/eeprom.dir/build.make CMakeFiles/eeprom.dir/build
.PHONY : eeprom/fast

#=============================================================================
# Target rules for targets named my_firmware

# Build rule for target.
my_firmware: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 my_firmware
.PHONY : my_firmware

# fast build rule for target.
my_firmware/fast:
	$(MAKE) -f CMakeFiles/my_firmware.dir/build.make CMakeFiles/my_firmware.dir/build
.PHONY : my_firmware/fast

#=============================================================================
# Target rules for targets named upload

# Build rule for target.
upload: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 upload
.PHONY : upload

# fast build rule for target.
upload/fast:
	$(MAKE) -f CMakeFiles/upload.dir/build.make CMakeFiles/upload.dir/build
.PHONY : upload/fast

#=============================================================================
# Target rules for targets named upload_eeprom

# Build rule for target.
upload_eeprom: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 upload_eeprom
.PHONY : upload_eeprom

# fast build rule for target.
upload_eeprom/fast:
	$(MAKE) -f CMakeFiles/upload_eeprom.dir/build.make CMakeFiles/upload_eeprom.dir/build
.PHONY : upload_eeprom/fast

src/astdio.o: src/astdio.c.o

.PHONY : src/astdio.o

# target to build an object file
src/astdio.c.o:
	$(MAKE) -f CMakeFiles/my_firmware.dir/build.make CMakeFiles/my_firmware.dir/src/astdio.c.o
.PHONY : src/astdio.c.o

src/astdio.i: src/astdio.c.i

.PHONY : src/astdio.i

# target to preprocess a source file
src/astdio.c.i:
	$(MAKE) -f CMakeFiles/my_firmware.dir/build.make CMakeFiles/my_firmware.dir/src/astdio.c.i
.PHONY : src/astdio.c.i

src/astdio.s: src/astdio.c.s

.PHONY : src/astdio.s

# target to generate assembly for a file
src/astdio.c.s:
	$(MAKE) -f CMakeFiles/my_firmware.dir/build.make CMakeFiles/my_firmware.dir/src/astdio.c.s
.PHONY : src/astdio.c.s

src/elm.o: src/elm.c.o

.PHONY : src/elm.o

# target to build an object file
src/elm.c.o:
	$(MAKE) -f CMakeFiles/my_firmware.dir/build.make CMakeFiles/my_firmware.dir/src/elm.c.o
.PHONY : src/elm.c.o

src/elm.i: src/elm.c.i

.PHONY : src/elm.i

# target to preprocess a source file
src/elm.c.i:
	$(MAKE) -f CMakeFiles/my_firmware.dir/build.make CMakeFiles/my_firmware.dir/src/elm.c.i
.PHONY : src/elm.c.i

src/elm.s: src/elm.c.s

.PHONY : src/elm.s

# target to generate assembly for a file
src/elm.c.s:
	$(MAKE) -f CMakeFiles/my_firmware.dir/build.make CMakeFiles/my_firmware.dir/src/elm.c.s
.PHONY : src/elm.c.s

src/fat.o: src/fat.c.o

.PHONY : src/fat.o

# target to build an object file
src/fat.c.o:
	$(MAKE) -f CMakeFiles/my_firmware.dir/build.make CMakeFiles/my_firmware.dir/src/fat.c.o
.PHONY : src/fat.c.o

src/fat.i: src/fat.c.i

.PHONY : src/fat.i

# target to preprocess a source file
src/fat.c.i:
	$(MAKE) -f CMakeFiles/my_firmware.dir/build.make CMakeFiles/my_firmware.dir/src/fat.c.i
.PHONY : src/fat.c.i

src/fat.s: src/fat.c.s

.PHONY : src/fat.s

# target to generate assembly for a file
src/fat.c.s:
	$(MAKE) -f CMakeFiles/my_firmware.dir/build.make CMakeFiles/my_firmware.dir/src/fat.c.s
.PHONY : src/fat.c.s

src/fifo.o: src/fifo.c.o

.PHONY : src/fifo.o

# target to build an object file
src/fifo.c.o:
	$(MAKE) -f CMakeFiles/my_firmware.dir/build.make CMakeFiles/my_firmware.dir/src/fifo.c.o
.PHONY : src/fifo.c.o

src/fifo.i: src/fifo.c.i

.PHONY : src/fifo.i

# target to preprocess a source file
src/fifo.c.i:
	$(MAKE) -f CMakeFiles/my_firmware.dir/build.make CMakeFiles/my_firmware.dir/src/fifo.c.i
.PHONY : src/fifo.c.i

src/fifo.s: src/fifo.c.s

.PHONY : src/fifo.s

# target to generate assembly for a file
src/fifo.c.s:
	$(MAKE) -f CMakeFiles/my_firmware.dir/build.make CMakeFiles/my_firmware.dir/src/fifo.c.s
.PHONY : src/fifo.c.s

src/io.o: src/io.c.o

.PHONY : src/io.o

# target to build an object file
src/io.c.o:
	$(MAKE) -f CMakeFiles/my_firmware.dir/build.make CMakeFiles/my_firmware.dir/src/io.c.o
.PHONY : src/io.c.o

src/io.i: src/io.c.i

.PHONY : src/io.i

# target to preprocess a source file
src/io.c.i:
	$(MAKE) -f CMakeFiles/my_firmware.dir/build.make CMakeFiles/my_firmware.dir/src/io.c.i
.PHONY : src/io.c.i

src/io.s: src/io.c.s

.PHONY : src/io.s

# target to generate assembly for a file
src/io.c.s:
	$(MAKE) -f CMakeFiles/my_firmware.dir/build.make CMakeFiles/my_firmware.dir/src/io.c.s
.PHONY : src/io.c.s

src/lcd.o: src/lcd.c.o

.PHONY : src/lcd.o

# target to build an object file
src/lcd.c.o:
	$(MAKE) -f CMakeFiles/my_firmware.dir/build.make CMakeFiles/my_firmware.dir/src/lcd.c.o
.PHONY : src/lcd.c.o

src/lcd.i: src/lcd.c.i

.PHONY : src/lcd.i

# target to preprocess a source file
src/lcd.c.i:
	$(MAKE) -f CMakeFiles/my_firmware.dir/build.make CMakeFiles/my_firmware.dir/src/lcd.c.i
.PHONY : src/lcd.c.i

src/lcd.s: src/lcd.c.s

.PHONY : src/lcd.s

# target to generate assembly for a file
src/lcd.c.s:
	$(MAKE) -f CMakeFiles/my_firmware.dir/build.make CMakeFiles/my_firmware.dir/src/lcd.c.s
.PHONY : src/lcd.c.s

src/list.o: src/list.c.o

.PHONY : src/list.o

# target to build an object file
src/list.c.o:
	$(MAKE) -f CMakeFiles/my_firmware.dir/build.make CMakeFiles/my_firmware.dir/src/list.c.o
.PHONY : src/list.c.o

src/list.i: src/list.c.i

.PHONY : src/list.i

# target to preprocess a source file
src/list.c.i:
	$(MAKE) -f CMakeFiles/my_firmware.dir/build.make CMakeFiles/my_firmware.dir/src/list.c.i
.PHONY : src/list.c.i

src/list.s: src/list.c.s

.PHONY : src/list.s

# target to generate assembly for a file
src/list.c.s:
	$(MAKE) -f CMakeFiles/my_firmware.dir/build.make CMakeFiles/my_firmware.dir/src/list.c.s
.PHONY : src/list.c.s

src/main.o: src/main.c.o

.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) -f CMakeFiles/my_firmware.dir/build.make CMakeFiles/my_firmware.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) -f CMakeFiles/my_firmware.dir/build.make CMakeFiles/my_firmware.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) -f CMakeFiles/my_firmware.dir/build.make CMakeFiles/my_firmware.dir/src/main.c.s
.PHONY : src/main.c.s

src/msg.o: src/msg.c.o

.PHONY : src/msg.o

# target to build an object file
src/msg.c.o:
	$(MAKE) -f CMakeFiles/my_firmware.dir/build.make CMakeFiles/my_firmware.dir/src/msg.c.o
.PHONY : src/msg.c.o

src/msg.i: src/msg.c.i

.PHONY : src/msg.i

# target to preprocess a source file
src/msg.c.i:
	$(MAKE) -f CMakeFiles/my_firmware.dir/build.make CMakeFiles/my_firmware.dir/src/msg.c.i
.PHONY : src/msg.c.i

src/msg.s: src/msg.c.s

.PHONY : src/msg.s

# target to generate assembly for a file
src/msg.c.s:
	$(MAKE) -f CMakeFiles/my_firmware.dir/build.make CMakeFiles/my_firmware.dir/src/msg.c.s
.PHONY : src/msg.c.s

src/obd.o: src/obd.c.o

.PHONY : src/obd.o

# target to build an object file
src/obd.c.o:
	$(MAKE) -f CMakeFiles/my_firmware.dir/build.make CMakeFiles/my_firmware.dir/src/obd.c.o
.PHONY : src/obd.c.o

src/obd.i: src/obd.c.i

.PHONY : src/obd.i

# target to preprocess a source file
src/obd.c.i:
	$(MAKE) -f CMakeFiles/my_firmware.dir/build.make CMakeFiles/my_firmware.dir/src/obd.c.i
.PHONY : src/obd.c.i

src/obd.s: src/obd.c.s

.PHONY : src/obd.s

# target to generate assembly for a file
src/obd.c.s:
	$(MAKE) -f CMakeFiles/my_firmware.dir/build.make CMakeFiles/my_firmware.dir/src/obd.c.s
.PHONY : src/obd.c.s

src/pins.o: src/pins.c.o

.PHONY : src/pins.o

# target to build an object file
src/pins.c.o:
	$(MAKE) -f CMakeFiles/my_firmware.dir/build.make CMakeFiles/my_firmware.dir/src/pins.c.o
.PHONY : src/pins.c.o

src/pins.i: src/pins.c.i

.PHONY : src/pins.i

# target to preprocess a source file
src/pins.c.i:
	$(MAKE) -f CMakeFiles/my_firmware.dir/build.make CMakeFiles/my_firmware.dir/src/pins.c.i
.PHONY : src/pins.c.i

src/pins.s: src/pins.c.s

.PHONY : src/pins.s

# target to generate assembly for a file
src/pins.c.s:
	$(MAKE) -f CMakeFiles/my_firmware.dir/build.make CMakeFiles/my_firmware.dir/src/pins.c.s
.PHONY : src/pins.c.s

src/sd.o: src/sd.c.o

.PHONY : src/sd.o

# target to build an object file
src/sd.c.o:
	$(MAKE) -f CMakeFiles/my_firmware.dir/build.make CMakeFiles/my_firmware.dir/src/sd.c.o
.PHONY : src/sd.c.o

src/sd.i: src/sd.c.i

.PHONY : src/sd.i

# target to preprocess a source file
src/sd.c.i:
	$(MAKE) -f CMakeFiles/my_firmware.dir/build.make CMakeFiles/my_firmware.dir/src/sd.c.i
.PHONY : src/sd.c.i

src/sd.s: src/sd.c.s

.PHONY : src/sd.s

# target to generate assembly for a file
src/sd.c.s:
	$(MAKE) -f CMakeFiles/my_firmware.dir/build.make CMakeFiles/my_firmware.dir/src/sd.c.s
.PHONY : src/sd.c.s

src/spi.o: src/spi.c.o

.PHONY : src/spi.o

# target to build an object file
src/spi.c.o:
	$(MAKE) -f CMakeFiles/my_firmware.dir/build.make CMakeFiles/my_firmware.dir/src/spi.c.o
.PHONY : src/spi.c.o

src/spi.i: src/spi.c.i

.PHONY : src/spi.i

# target to preprocess a source file
src/spi.c.i:
	$(MAKE) -f CMakeFiles/my_firmware.dir/build.make CMakeFiles/my_firmware.dir/src/spi.c.i
.PHONY : src/spi.c.i

src/spi.s: src/spi.c.s

.PHONY : src/spi.s

# target to generate assembly for a file
src/spi.c.s:
	$(MAKE) -f CMakeFiles/my_firmware.dir/build.make CMakeFiles/my_firmware.dir/src/spi.c.s
.PHONY : src/spi.c.s

src/time.o: src/time.c.o

.PHONY : src/time.o

# target to build an object file
src/time.c.o:
	$(MAKE) -f CMakeFiles/my_firmware.dir/build.make CMakeFiles/my_firmware.dir/src/time.c.o
.PHONY : src/time.c.o

src/time.i: src/time.c.i

.PHONY : src/time.i

# target to preprocess a source file
src/time.c.i:
	$(MAKE) -f CMakeFiles/my_firmware.dir/build.make CMakeFiles/my_firmware.dir/src/time.c.i
.PHONY : src/time.c.i

src/time.s: src/time.c.s

.PHONY : src/time.s

# target to generate assembly for a file
src/time.c.s:
	$(MAKE) -f CMakeFiles/my_firmware.dir/build.make CMakeFiles/my_firmware.dir/src/time.c.s
.PHONY : src/time.c.s

src/uart.o: src/uart.c.o

.PHONY : src/uart.o

# target to build an object file
src/uart.c.o:
	$(MAKE) -f CMakeFiles/my_firmware.dir/build.make CMakeFiles/my_firmware.dir/src/uart.c.o
.PHONY : src/uart.c.o

src/uart.i: src/uart.c.i

.PHONY : src/uart.i

# target to preprocess a source file
src/uart.c.i:
	$(MAKE) -f CMakeFiles/my_firmware.dir/build.make CMakeFiles/my_firmware.dir/src/uart.c.i
.PHONY : src/uart.c.i

src/uart.s: src/uart.c.s

.PHONY : src/uart.s

# target to generate assembly for a file
src/uart.c.s:
	$(MAKE) -f CMakeFiles/my_firmware.dir/build.make CMakeFiles/my_firmware.dir/src/uart.c.s
.PHONY : src/uart.c.s

src/utils.o: src/utils.c.o

.PHONY : src/utils.o

# target to build an object file
src/utils.c.o:
	$(MAKE) -f CMakeFiles/my_firmware.dir/build.make CMakeFiles/my_firmware.dir/src/utils.c.o
.PHONY : src/utils.c.o

src/utils.i: src/utils.c.i

.PHONY : src/utils.i

# target to preprocess a source file
src/utils.c.i:
	$(MAKE) -f CMakeFiles/my_firmware.dir/build.make CMakeFiles/my_firmware.dir/src/utils.c.i
.PHONY : src/utils.c.i

src/utils.s: src/utils.c.s

.PHONY : src/utils.s

# target to generate assembly for a file
src/utils.c.s:
	$(MAKE) -f CMakeFiles/my_firmware.dir/build.make CMakeFiles/my_firmware.dir/src/utils.c.s
.PHONY : src/utils.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... strip"
	@echo "... fuses"
	@echo "... hex"
	@echo "... eeprom"
	@echo "... my_firmware"
	@echo "... upload"
	@echo "... upload_eeprom"
	@echo "... src/astdio.o"
	@echo "... src/astdio.i"
	@echo "... src/astdio.s"
	@echo "... src/elm.o"
	@echo "... src/elm.i"
	@echo "... src/elm.s"
	@echo "... src/fat.o"
	@echo "... src/fat.i"
	@echo "... src/fat.s"
	@echo "... src/fifo.o"
	@echo "... src/fifo.i"
	@echo "... src/fifo.s"
	@echo "... src/io.o"
	@echo "... src/io.i"
	@echo "... src/io.s"
	@echo "... src/lcd.o"
	@echo "... src/lcd.i"
	@echo "... src/lcd.s"
	@echo "... src/list.o"
	@echo "... src/list.i"
	@echo "... src/list.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/msg.o"
	@echo "... src/msg.i"
	@echo "... src/msg.s"
	@echo "... src/obd.o"
	@echo "... src/obd.i"
	@echo "... src/obd.s"
	@echo "... src/pins.o"
	@echo "... src/pins.i"
	@echo "... src/pins.s"
	@echo "... src/sd.o"
	@echo "... src/sd.i"
	@echo "... src/sd.s"
	@echo "... src/spi.o"
	@echo "... src/spi.i"
	@echo "... src/spi.s"
	@echo "... src/time.o"
	@echo "... src/time.i"
	@echo "... src/time.s"
	@echo "... src/uart.o"
	@echo "... src/uart.i"
	@echo "... src/uart.s"
	@echo "... src/utils.o"
	@echo "... src/utils.i"
	@echo "... src/utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

